repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=102400']  # 100MB in KB
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=120]
        files: \.py$
        exclude: ^(deprecated/|dust3r/|layerpano3d/|FLUX-Controlnet-Inpainting/|imgs/|__pycache__/)

-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        args: [--max-line-length=120, --aggressive, --verbose, --diff]
        files: \.py$
        exclude: ^(deprecated/|dust3r/|layerpano3d/|FLUX-Controlnet-Inpainting/|imgs/|__pycache__/)
        verbose: true
